### PR TITLE
BREAKING CHANGE(WP-578): create list of links from array, BEM complaiant

### PR DESCRIPTION
**Pull request by umbobabo**
This PR expand the capability of menus creation of the admin bar to a list of buttons or a select dropdwon.
https://jira.economist.com/browse/WP-578 .

### CODE REVIEW

**Comment by matusmarcin** [comment]
Looking at this. In the meantime, what's wrong with the build?

**Comment by matusmarcin** [comment]
Code looks good 👍 

Are we updating this page as well? 
https://economist-components.github.io/component-admin-bar/ 

Just out of curiosity: Where does that live? Or does it happen automagically?

**Comment by umbobabo** [comment]
@matusmarcin The problem with the build was due to missing proptypes for sub components.
This https://economist-components.github.io/component-admin-bar/ is a github page created from the branch gh-pages https://pages.github.com/

**Comment by umbobabo** [comment]
I reverted back that change on the version. Since we introduced semantic-release we stopped bump the version on the package.json as a reminder to not publish the package manually.
Merge if you are happy please.

**Pull request merged**
